---
title: "Bioc package list"
author: ""
date: "`r Sys.time()`"
output:
  rmarkdown::html_document:
    highlight: pygments
    toc: true
    toc_float: false
    toc_depth: 3
    fig_width: 5
    number_sections: false
    theme: united
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
    library(DT)
    library(BiocPkgTools)
    library(dplyr)
    library(tidyr)
    library(igraph)
    library(ggplot2)
    library(ggrepel)
    library(plotly)
})
```

# Get list of packages

```{r}
bpi <- biocPkgList(version = "devel")
```

# Get and summarize download stats

```{r}
ds <- biocDownloadStats(pkgType = "software")
ads <- anacondaDownloadStats()

okd = c("2024:Nov", "2024:Dec", "2025:Apr", "2025:Aug", "2025:Feb", "2025:Jan", 
"2025:Jul", "2025:Jun", "2025:Mar", "2025:May", "2025:Oct", "2025:Sep")

## Total downloads Nov-24 to Nov-25
ds <- ds |> mutate(ymo = paste0(Year, ":", Month)) |>
    dplyr::filter(ymo %in% okd) |>
    dplyr::group_by(Package) |>
    dplyr::summarize(NbDownloadsBioc = sum(Nb_of_downloads))
ads <- ads |> mutate(ymo = paste0(Year, ":", Month)) |>
    dplyr::filter(ymo %in% okd) |>
    dplyr::group_by(Package) |>
    dplyr::summarize(NbDownloadsConda = sum(Nb_of_downloads))
```

# Find dependencies among packages

```{r}
## Build package dependency graph
depdf <- BiocPkgTools::buildPkgDependencyDataFrame(
    repo = c("BioCsoft", "CRAN"),
    dependencies = c("Depends", "Imports")
)
## ... edges go from package to upstream dependencies/imports
g <- BiocPkgTools::buildPkgDependencyIgraph(depdf)

## Get all packages (will include both Bioc and CRAN packages, if the latter 
## are dependencies for Bioc packages)
pkgs <- setdiff(names(igraph::V(g)), "")
length(pkgs)

## Get Bioc packages
bps <- bpi$Package
bps <- intersect(bps, pkgs)
length(bps)

## Initialize dependency matrix among Bioc packages
## Package in row depends on/imports packages in columns
# depmat <- matrix(0, nrow = length(pkgs), ncol = length(pkgs))
# rownames(depmat) <- colnames(depmat) <- pkgs
depmat <- matrix(0, nrow = length(bps), ncol = length(bps))
rownames(depmat) <- colnames(depmat) <- bps

## Find dependencies for each packages (direct and indirect)
for (p in bps) {
    sc <- igraph::subcomponent(g, p, mode = "out")
    depmat[p, intersect(setdiff(names(sc), ""), bps)] <- 1
    # depmat[p, setdiff(names(sc), "")] <- 1
}

## Subset dependency matrix to Bioc packages
depmat_bioc <- depmat[bps, bps]

## Column sums ("how many packages depend - directly or indirectly - 
## on a given package"). Subtract 1 to not include the package itself.
cs <- colSums(depmat_bioc) - 1

## Number of direct reverse dependencies
## ... for each node N, find all other nodes with an edge directly to N
##     (i.e., depending directly on N)
drevdeps <- igraph::ego(g, nodes = V(g), order = 1, mode = "in")
drevdeps <- lapply(drevdeps, function(w) intersect(names(w), bps))
## Get number of packages depending directly on each package (subtract 1 to not 
## count the package itself)
drevdeps <- vapply(drevdeps, length, 0) - 1
names(drevdeps) <- names(V(g))
drevdeps <- drevdeps[bps]
```

# Make summary table

```{r}
bpisub <- bpi |>
    dplyr::select(Package, Maintainer, dependencyCount) |>
    dplyr::left_join(ds, by = "Package") |>
    dplyr::left_join(ads, by = "Package") |>
    dplyr::mutate(NbDownloadsConda = replace_na(NbDownloadsConda, 0),
                  NbDownloadsBioc = replace_na(NbDownloadsBioc, 0)) |>
    dplyr::mutate(NbDownloadsBiocConda = NbDownloadsBioc + 
                      NbDownloadsConda)

## Add number of downstream dependencies (direct or direct + indirect)
bpisub$NbDependentPkgs <- cs[bpisub$Package]
bpisub$NbDirDependentPkgs <- drevdeps[bpisub$Package]

## Get download counts for downstream dependencies
diag(depmat_bioc) <- 0
NbDownloadsBiocDepPkgs <- (rbind(bpisub$NbDownloadsBioc[match(
    rownames(depmat_bioc), bpisub$Package)]) %*% depmat_bioc)[1, ]
NbDownloadsCondaDepPkgs <- (rbind(bpisub$NbDownloadsConda[match(
    rownames(depmat_bioc), bpisub$Package)]) %*% depmat_bioc)[1, ]

bpisub$NbDownloadsBiocDepPkgs <-
    NbDownloadsBiocDepPkgs[bpisub$Package]
bpisub$NbDownloadsCondaDepPkgs <- 
    NbDownloadsCondaDepPkgs[bpisub$Package]

bpisub <- bpisub |>
    dplyr::mutate(NbDownloadsBiocCondaDepPkgs =
                      NbDownloadsBiocDepPkgs + 
                      NbDownloadsCondaDepPkgs)

bpisub <- as.data.frame(bpisub)

DT::datatable(bpisub |> dplyr::arrange(desc(NbDownloadsBiocConda)), 
              extensions = "FixedColumns",
              options = list(scrollX = TRUE, fixedColumns = list(leftColumns = 2), 
                             pageLength = 25))
```

# Plots

```{r, fig.width = 8, fig.height = 7}
ggplot(bpisub, aes(x = NbDownloadsBioc, y = NbDownloadsConda)) + 
    geom_point(size = 3, alpha = 0.5) + theme_bw() + 
    geom_text_repel(
        data = bpisub |> 
            dplyr::filter(
                (NbDownloadsBioc > 750000 & NbDownloadsConda < 50000) |
                    (NbDownloadsBioc < 500000 & NbDownloadsConda > 100000)),
        aes(label = Package), max.overlaps = Inf, size = 4,
        min.segment.length = 0.1) + 
    labs(x = "Number of Bioc downloads for indicated package",
         y = "Number of conda downloads for indicated package")
## ... interactive version
ggplotly(
    ggplot(bpisub, aes(x = NbDownloadsBioc, y = NbDownloadsConda, 
                       label = Package)) + 
        geom_point(size = 3, alpha = 0.5) + theme_bw() + 
    labs(x = "Number of Bioc downloads for indicated package",
         y = "Number of conda downloads for indicated package")
)

ggplot(bpisub, aes(x = NbDownloadsBiocConda,
                   y = NbDownloadsBiocCondaDepPkgs)) + 
    geom_abline(slope = 1, intercept = 0, color = "grey", linetype = "dotted") + 
    geom_point(size = 3, alpha = 0.5) + theme_bw() + 
    geom_text_repel(
        data = bpisub |> 
            dplyr::filter(
                (NbDownloadsBiocConda > 750000) |
                    (NbDownloadsBiocConda < 500000 &
                         NbDownloadsBiocCondaDepPkgs > 5000000) | 
                    (NbDownloadsBiocConda < 250000 &
                         NbDownloadsBiocCondaDepPkgs > 3000000)), 
        aes(label = Package), max.overlaps = Inf, size = 4,
        min.segment.length = 0.1) + 
    labs(x = "Number of downloads from Bioc + conda for indicated package",
         y = "Number of downloads from Bioc + conda\nfor downstream dependencies of indicated package")

ggplot(bpisub, aes(x = NbDirDependentPkgs, y = NbDependentPkgs)) + 
    geom_abline(slope = 1, intercept = 0, color = "grey", linetype = "dotted") + 
    geom_point(size = 3, alpha = 0.5) + theme_bw() + 
    geom_text_repel(
        data = bpisub |> 
            dplyr::filter(
                (NbDirDependentPkgs > 120) |
                    (NbDirDependentPkgs < 120 &
                         NbDependentPkgs > 300)), 
        aes(label = Package), max.overlaps = Inf, size = 4,
        min.segment.length = 0.1) + 
    labs(x = "Number of packages directly importing indicated package",
         y = "Number of packages directly or indirectly\nimporting indicated package")
```

# Session info

```{r}
sessionInfo()
```

